# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 301648a3aa13663238d0488e8d986ae25cd63c46ad7f52b640c746b74a0f1819e79f7ca967cb6e8c7da170295665c47ffcd2eb385ff42abaf9babbf0bc60d7db

test:
  secret_key_base: 949b1566007543073d2ab394bcc4f5216a7fc68f431207557266331ba7ee7597bd5e85ff4edfd0291412f5075d0933d7eae2a2a18a367681429ac04010d2d621

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
